### ISSUE TITLE
Project Name conflict with Johnny-Five

### ISSUE THREAD

**Issue by rwaldron** [googlearchive/numberhtml5-app#1]
Hey guys,

For several months I've been developing a JavaScript Arduino (and Lego NXT via NXT Multiplexer) programming framework for Node.js, called Johnny Five. My project is also JavaScript only, but has no browser dependency.

The project repo is here: 

https://github.com/rwldrn/johnny-five

I've published blog posts:

[JavaScript: Arduino Programming on Node.js](http://weblog.bocoup.com/javascript-arduino-programming-with-nodejs/)
[JavaScript: Arduino Servo Control Tutorial](http://weblog.bocoup.com/javascript-arduino-servo-control-tutorial/)
[JavaScript: Arduino Slide Controlling a Servo Tutorial](http://weblog.bocoup.com/javascript-arduino-slide-controlling-servo-tutorial/)

Coverage in .net magazine:

[10 things you didn't know JavaScript could do](http://www.netmagazine.com/features/10-things-you-didnt-know-javascript-could-do)

I am also speaking next week at a conference in Portland, OR about this project.

I'd like to kindly and respectfully ask you to change the name of your project to something that will distinctly identify it as something different from my project.

Thanks in advance :)

**Comment by eliperelman** [comment]
+1

**Comment by gf3** [comment]
``` clojure
(swap! *sentiment* inc)
```

**Comment by wesbos** [comment]
+1

**Comment by pkarl** [comment]
+1

**Comment by unruthless** [comment]
+1

**Comment by sflitcroft** [comment]
+1

**Comment by matthopson** [comment]
+1

**Comment by ajpiano** [comment]
+1

**Comment by aackerman** [comment]
+1

**Comment by joshlangner** [comment]
+1. For crying out loud.

**Comment by rupl** [comment]
+1

**Comment by miketaylr** [comment]
This is kind of a bummer to see. I've been reading about @rwldrn's Johnny Five blog posts on the Bocoup blog and from his twitter stream for weeks now.

A project name change would be a nice gesture, to say the least. I found a huuuge list of fictional robots and androids to choose from: https://en.wikipedia.org/wiki/List_of_fictional_robots_and_androids. Here's a few you could mash up with "html5" to serve as inspiration:

Gnut, Gort, Boilerplate, Bubo (omg obligaory cute robot owl logo), Alpha 5, etc.

**Comment by filaraujo** [comment]
+1

**Comment by jdalton** [comment]
+1 I dig Bubo, [youtube.com/watch?v=rzKhqt5IRnM](http://www.youtube.com/watch?v=rzKhqt5IRnM#t=0m35s), but I'm a sucker for cute mechanical owls.

**Comment by paultag** [comment]
+1

**Comment by rmurphey** [comment]
+1, seems the name is pretty confusing considering the existing body of work that @rwldrn referenced, which seems to significantly predate this repo :)

**Comment by boazsender** [comment]
+1

**Comment by JamyGolden** [comment]
+1

**Comment by chapel** [comment]
+1

Github needs a ^5 button or something.

**Comment by dherman** [comment]
+1 This project would probably be better off anyway with its own more clearly distinct identity.

**Comment by Gavrisimo** [comment]
+1

**Comment by jonathantneal** [comment]
pluhswuhn

**Comment by treffynnon** [comment]
@miketaylr and @jdalton are you sure bubo is such a good idea? It is a [painful swelling of the lymph nodes](http://en.wikipedia.org/wiki/Bubo) commonly associated with the black death. Agree with the rename though.

**Comment by jdalton** [comment]
@treffynnon 

![reaction](http://karlmac.com/wp-content/uploads/2011/11/ysjIk.gif)

**Comment by alexgraul** [comment]
+1

**Comment by franckuser16** [comment]
+1

**Comment by Inviz** [comment]
+1

**Comment by jrgifford** [comment]
+1

**Comment by andrewbrooks** [comment]
+1

**Comment by mennovanslooten** [comment]
+1

**Comment by twneale** [comment]
+1  Ya, sorry dudes, Rick had this one first

**Comment by ghost** [comment]
+1

**Comment by dariusk** [comment]
+1

**Comment by whylom** [comment]
+1

**Comment by ralphholzmann** [comment]
When I first opened this page I thought

`Oh sweet! Google Chrome is using @rwldrn's framework for a demo!`

only to find out that that is not the case.

+1 on the name change.

**Comment by codecaffeine** [comment]
+1

**Comment by eliperelman** [comment]
![What have I started...](http://i.qkme.me/3pwufg.jpg)

**Comment by PaulKinlan** [comment]
I did a search for naming conflicts before launching this sample code and because the names are different this project didn't come up.  I personally think that the names are different enough and that this is just a simple demo of the platform, not a full API and it is just the name of a repo that it won't cause that much confusion.

That being said, I am also looking for another name but there a number of logistical things that I have to get sorted first which are a lot more complicated that just renaming the repo (including seeing my family who I have not seen for 3 weeks).

In the meantime, I am super happy to put a full reference to the Johnny5 framework in the README to disambiguate.

**Comment by rwaldron** [comment]
I'd be curious to know what you searched for, "javascript johnny five", "javascript johnny 5" and "johnny five" all return results that include my project. Renaming a repo is really easy - it's a feature built into github's repo admin.

http://www.google.com/search?q=javascript+johnny+five

**Comment by gnarf** [comment]
:+1:

**Comment by Wilto** [comment]
@rwldrn has dibs, fair and square.

+1

**Comment by darcyclarke** [comment]
+1

**Comment by addyosmani** [comment]
For obvious reasons, I'm going to refrain from +/-1ing, but here are my two cents :)

Rick's johnny-five project of course came first - I don't think anyone would dispute that. That said, I imagine that it's a challenge for anyone wishing to create a Johnny-5 hommage in this space to come up with a suitable name that is a) discoverable and b) doesn't clash too much with existing projects. I'm sure @PaulKinlan and co didn't have that intention.

Johnnyhtml5-sample is a pretty cute take on the name, but perhaps an alternative to +1s would be suggestions of names that could be used which wouldn't clash as much? There may have already been some..

That would at least give the repo owners some food for thought, though it is ultimately their decision what they do :)

**Comment by dherman** [comment]
Hi @addyosmani! I'm also absolutely sure nobody meant any harm. But the right thing to do is for the team working on this project to find a new name — which it sounds like @PaulKinlan is willing to do.

@miketaylr did provide alterative suggestions in this thread. But I don't think it's the responsibility of @rwldrn or people backing him up here to find that new name. If I were to come out with a new project I decided to call, say, CoffeeScriptr, particularly if its purpose was similar to CoffeeScript, it wouldn't be anyone else's responsibility but mine to pick a new name. I'm sure Google has plenty of resources for branding, and I'm sure Johnny Five isn't the only friendly robot out there (even if he was my childhood hero). Meanwhile, names and branding are valuable to a project, and whether you like the HTML5 pun or not, there's just no disputing that Rick's is the first JS robotics project to use that reference.

Dave

**Comment by PaulKinlan** [comment]
@rwldrn I searched "johnny html5" and "Javascript Mindstorm".  

Anyway, like I said, it is not the repo name change that is hard, it is the fact that we have just finished Google I/O, people are taking well earned vacation after 5 months solid hard work and I will need all the docs and links and videos updated with the project reference and I will need to get them to do that, so in the meantime I can point to the Johnny 5 repository in the project from the readme.

**Comment by paulirish** [comment]
@PaulKinlan we can move this repo to a new name, and throw back up a stub repo that points to the new location of this (as well as rick's)

That way no links are broken and the project name can stand a bit more unique.

**Comment by PaulKinlan** [comment]
@paulirish good idea, seems like the quickest way.  I can do that now and sort out the links as we go.

**Comment by PaulKinlan** [comment]
I am going to change the name to NumberHTML5, make a repo called johnnyhtml5-sample that disambiguates both projects until we get the links/docs sorted.

**Comment by rwaldron** [comment]
Thanks guys - I really appreciate your consideration and understanding :)
